#!/usr/bin/env python3
"""Generate the nice!view LVGL image source from the portrait PBM artwork."""

from pathlib import Path

SOURCE_WIDTH = 68
SOURCE_HEIGHT = 140
SCRIPT_DIR = Path(__file__).resolve().parent
SOURCE = SCRIPT_DIR / "orca.pbm"
OUTPUT = SCRIPT_DIR.parent / "widgets" / "art.c"


def read_p1(path: Path) -> list[list[int]]:
    tokens: list[str] = []
    for line in path.read_text(encoding="ascii").splitlines():
        tokens.extend(line.split("#", 1)[0].split())

    if len(tokens) < 3 or tokens[0] != "P1":
        raise ValueError(f"{path} must be an ASCII P1 PBM image")

    width, height = map(int, tokens[1:3])
    if (width, height) != (SOURCE_WIDTH, SOURCE_HEIGHT):
        raise ValueError(
            f"{path} must be {SOURCE_WIDTH}x{SOURCE_HEIGHT}, got {width}x{height}"
        )

    pixels = [int(value) for value in tokens[3:]]
    if len(pixels) != width * height or any(value not in (0, 1) for value in pixels):
        raise ValueError(f"{path} contains invalid PBM pixel data")

    return [pixels[offset : offset + width] for offset in range(0, len(pixels), width)]


def rotate_clockwise(source: list[list[int]]) -> list[list[int]]:
    height = len(source)
    width = len(source[0])
    return [[source[height - 1 - x][y] for x in range(height)] for y in range(width)]


def pack_lvgl_indexed_1bit(source: list[list[int]]) -> bytes:
    packed = bytearray()
    width = len(source[0])

    for row in source:
        for offset in range(0, width, 8):
            value = 0
            for bit in range(8):
                value <<= 1
                x = offset + bit
                if x < width:
                    # PBM uses 1 for black. LVGL palette index 0 is black and
                    # index 1 is white, so the packed image bit is inverted.
                    value |= 1 - row[x]
            packed.append(value)

    return bytes(packed)


def format_bytes(data: bytes) -> str:
    values = [f"0x{value:02x}" for value in data]
    return "\n".join(
        "    " + ", ".join(values[offset : offset + 16]) + ","
        for offset in range(0, len(values), 16)
    )


def main() -> None:
    portrait = read_p1(SOURCE)
    firmware_image = rotate_clockwise(portrait)
    data = pack_lvgl_indexed_1bit(firmware_image)
    width = len(firmware_image[0])
    height = len(firmware_image)
    expected_size = ((width + 7) // 8) * height
    if len(data) != expected_size:
        raise AssertionError(f"packed {len(data)} bytes, expected {expected_size}")

    output = f"""/*
 * Generated by artwork/generate_art.py from artwork/orca.pbm.
 * Do not edit this file directly.
 */

#include <lvgl.h>

#ifndef LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_MEM_ALIGN
#endif

#ifndef LV_ATTRIBUTE_IMG_ORCA
#define LV_ATTRIBUTE_IMG_ORCA
#endif

const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST LV_ATTRIBUTE_IMG_ORCA uint8_t orca_map[] = {{
#if CONFIG_NICE_VIEW_WIDGET_INVERTED
    0xff, 0xff, 0xff, 0xff, /* Color of index 0 */
    0x00, 0x00, 0x00, 0xff, /* Color of index 1 */
#else
    0x00, 0x00, 0x00, 0xff, /* Color of index 0 */
    0xff, 0xff, 0xff, 0xff, /* Color of index 1 */
#endif

{format_bytes(data)}
}};

const lv_img_dsc_t orca = {{
    .header.cf = LV_IMG_CF_INDEXED_1BIT,
    .header.always_zero = 0,
    .header.reserved = 0,
    .header.w = {width},
    .header.h = {height},
    .data_size = sizeof(orca_map),
    .data = orca_map,
}};
"""
    OUTPUT.write_text(output, encoding="ascii")


if __name__ == "__main__":
    main()
